parameters:
    bisonlab_user.roles:
        ROLE_USER:
            label: Plain User
            description: "The default user role"
            admin: false
            default: true
            enabled: true
        ROLE_ADMIN:
            label: Admin
            description: "The default admin role"
            admin: true
            enabled: true
            default: false
        ROLE_SUPER_ADMIN:
            label: Superadmin
            description: "The super, do all, admin role"
            admin: true
            enabled: true
            default: false
        ROLE_DISABLED:
            label: Disabled
            description: "The sad, do nothing role"
            admin: false
            enabled: false
            default: false
    # Mainly/Only for password reset mail.
    bisonlab_user.mailfrom: "foo@bar.local"
    bisonlab_user.mailname: "BisonLab Reset password"

# If you want to use this here, remove the reset_password.yaml in your app.
# Or just copy this to it and uncomment

#symfonycasts_reset_password:
#    request_password_repository: BisonLab\UserBundle\Repository\ResetPasswordRequestRepository
#    lifetime: 3600
#    throttle_limit: 3600
#    enable_garbage_collection: true
